import rrdtool
ret = rrdtool.graph( "metric.png", "--start", "-9000", "--vertical-label=Num",
		'--watermark=Path Computation ',
		"--slope-mode",
		"--no-gridfit",
		"--title=Packet Rates",
		"-w 1000",
		"-h 600",
		"--alt-autoscale",
		"DEF:m1_num=lib/rrd/packet_rate.rrd:NodeId-2:AVERAGE",
		"DEF:m2_num=lib/rrd/packet_rate.rrd:NodeId-3:AVERAGE",
		"DEF:m3_num=lib/rrd/packet_rate.rrd:NodeId-4:AVERAGE",
		"DEF:m4_num=lib/rrd/packet_rate.rrd:NodeId-5:AVERAGE",
		#"DEF:m5_num=lib/rrd/packet_rate.rrd:NodeId-6:AVERAGE",
		#"DEF:m6_num=lib/rrd/packet_rate.rrd:NodeId-7:AVERAGE",
		#"DEF:m7_num=lib/rrd/packet_rate.rrd:NodeId-8:AVERAGE",
		#"DEF:m8_num=lib/rrd/packet_rate.rrd:NodeId-9:AVERAGE",
		"LINE4:m1_num#a6cee3:aaaa\:\:200\:0\:0\:2",
		"LINE4:m2_num#1f78b4:aaaa\:\:200\:0\:0\:3",
		"LINE4:m3_num#b2df8a:aaaa\:\:200\:0\:0\:4",
		"LINE4:m4_num#33a02c:aaaa\:\:200\:0\:0\:5")
		#"LINE4:m4_num#33a02c:aaaa\:\:200\:0\:0\:5",
		#"LINE4:m5_num#fb9a99:aaaa\:\:200\:0\:0\:6",
		#"LINE4:m6_num#e31a1c:aaaa\:\:200\:0\:0\:7",
		#"LINE4:m7_num#fdbf6f:aaaa\:\:200\:0\:0\:8")
		#"LINE4:m8_num#ff7f00:aaaa\:\:200\:0\:0\:9")
ret = rrdtool.graph( "metric-pdr.png", "--start", "-9000", "--vertical-label=Num",
		'--watermark=Path Computation ',
		"--slope-mode",
		"--title=Packet Rates",
		"-w 1000",
		"-h 400",
		"--upper-limit=100",
		"--lower-limit=94",
		"--rigid",
		#"--color=CANVAS#000000",
		#"--color=GRID#FFFFFF",
		"--alt-autoscale-min",
		"--no-gridfit",
		"DEF:avg=lib/rrd/packet_delivery_rate.rrd:pdr:AVERAGE",
		"AREA:avg#004D4D77:Average Network PDR",
		"LINE3:avg#004D4D")
